"""Write a measured configuration out as C the firmware can compile."""
from __future__ import annotations

from .fit import CamFit, WheelFit

HEADER = """\
/* GENERATED by tools/trigger from a capture. Do not edit by hand.
 *
 * {provenance}
 *
 * The wheel geometry and the cam pattern SHAPES below are measurements.
 * The absolute references -- gap_to_tdc_deg, and where each cam pattern
 * sits in the 720-degree cycle -- are not derivable from crank and cam
 * signals and were supplied by the operator from a bench procedure. See
 * tools/trigger/PROCEDURE.md.
 */
#include "decoder.h"

dec_config_t decoder_config_measured(void)
{{
    dec_config_t c;
    for (u32 i = 0; i < sizeof(c); i++) {{
        ((u8 *)&c)[i] = 0;
    }}
    c.measured = true;
"""


def emit_c(
    wheel: WheelFit,
    cams: list[tuple[CamFit, float, float, float]],
    *,
    gap_to_tdc_deg: float,
    provenance: str = "source capture not recorded",
) -> str:
    """Render the C. `cams` is (fit, angle of edge 0, adv_min, adv_max)."""
    out = [HEADER.format(provenance=provenance)]
    out.append(f"    c.teeth_total = {wheel.teeth_total};")
    out.append(f"    c.teeth_missing = {wheel.teeth_missing};")
    out.append("    c.gap_ratio = 1.6f;")
    out.append("    c.noise_ratio = 0.45f;")
    out.append(f"    c.gap_to_tdc_deg = {gap_to_tdc_deg:.2f}f;")
    out.append("")

    for idx, (cam, first_deg, adv_min, adv_max) in enumerate(cams):
        # Tolerance from measured jitter, with a floor: a capture taken at
        # one steady speed understates what a real engine does.
        tol = max(4.0, 3.0 * cam.jitter_deg)
        out.append(f"    /* {cam.name}: {cam.cycles_seen} cycles, "
                   f"jitter {cam.jitter_deg:.2f} deg */")
        out.append(f"    c.cam[{idx}].n_edges = {cam.n_edges};")
        angle = first_deg
        for e in range(cam.n_edges):
            out.append(
                f"    c.cam[{idx}].e[{e}].angle_deg = {angle % 720.0:.2f}f; "
                f"c.cam[{idx}].e[{e}].rising = "
                f"{'true' if cam.rising[e] else 'false'};"
            )
            angle += cam.intervals_deg[e]
        out.append(f"    c.cam[{idx}].adv_min_deg = {adv_min:.1f}f;")
        out.append(f"    c.cam[{idx}].adv_max_deg = {adv_max:.1f}f;")
        out.append(f"    c.cam[{idx}].match_tol_deg = {tol:.1f}f;")
        out.append(f"    c.cam[{idx}].slew_max_dps = 400.0f;")
        out.append("")

    out.append("    return c;")
    out.append("}")
    return "\n".join(out) + "\n"
