"""The start-up screen: the VE surface, drawn live while the app loads.

Not a QSplashScreen -- that is a card floating on the desktop in front of
nothing. This is an overlay filling the whole window, painting the same
surface the 3D table view paints, with the values moving as though a sweep
were being logged. It holds for a few seconds and fades into the
application underneath.

The motion is in three parts: the surface rises out of a flat plane column
by column across the rpm axis, then a slow wave travels over it while the
camera drifts round, then everything eases to rest at the angle the cover
art uses.

The brand arrives over the top of that, in its own two parts: the lambda
fades up once the surface has built, and the wordmark then slides out from
behind it to the right, revealed by a moving edge rather than flown in.
Both are drawn from tuner/ui/assets/, generated by tools/make_brand.py.
"""
import math

import numpy as np
from PySide6.QtCore import (QEasingCurve, QElapsedTimer, QEvent, QPropertyAnimation,
                            QRect, QRectF, Qt, QTimer)
from PySide6.QtGui import QColor, QFont, QPainter, QPen, QPixmap
from PySide6.QtWidgets import QGraphicsOpacityEffect, QWidget

from .. import APP_VERSION
from .assets import asset
from .surface_paint import project, quad_polys

BG = QColor("#202020")
EDGE = QColor("#3A3A3A")
INK = QColor("#F0F0F0")
SUB = QColor("#9A9A9A")
DIM = QColor("#6A6A6A")

HOLD_MS = 5000
FADE_MS = 280
BUILD_MS = 1200          # the surface rising out of the plane
SETTLE_MS = 700          # motion easing to rest at the end
FRAME_MS = 33            # ~30 fps
INPUT_GRACE_MS = 1200    # see mousePressEvent
NX, NY = 20, 14          # 247 quads a frame; the 3D view does ~400 interactively
ZS = 0.62

# The brand, over the surface. The mark waits for the build to finish so
# it does not compete with it; the wordmark follows while the mark is
# still settling, which reads as one movement rather than two.
MARK_AT_MS = 1400
MARK_IN_MS = 600
WORD_AT_MS = 1950
WORD_IN_MS = 520
MARK_H = 0.150           # mark height, as a fraction of the window
MARK_BASE = 0.800        # its baseline, likewise
MARK_LEFT = 0.070        # left margin for the whole lockup
WORD_GAP = 0.26          # mark-to-wordmark gap, in mark heights
WORD_CAP = 0.40          # wordmark cap height, in mark heights


def _ease(x):
    x = min(max(x, 0.0), 1.0)
    return x * x * (3.0 - 2.0 * x)


def ve_surface(nx=NX, ny=NY):
    """The truth surface the simulator calibrates against, with the local
    structure a real head has. Imported lazily so a missing tqmodel cannot
    stop the application starting."""
    from tqmodel.synth import truth_ve

    gx, gy = np.meshgrid(np.linspace(800.0, 7200.0, nx), np.linspace(30.0, 240.0, ny))
    return (np.asarray(truth_ve(gx, gy), dtype=float)
            + 0.045 * np.sin(gx / 900.0) * np.cos(gy / 95.0)
            + 0.030 * np.exp(-((gx - 3100.0) / 900.0) ** 2) * np.sin(gy / 60.0)
            - 0.035 * np.exp(-((gx - 6200.0) / 700.0) ** 2))


class IntroOverlay(QWidget):
    """Covers its parent and animates the surface until dismissed."""

    def __init__(self, parent, hold_ms=HOLD_MS, animate=True):
        super().__init__(parent)
        self.hold_ms = max(int(hold_ms), 0)
        self.status = ""
        self._fallback = None
        self._scaled = None
        self._timer = None
        self._done = False
        self._mark = None
        self._word = None

        self.base = ve_surface() if animate else None
        if self.base is not None:
            self.flat = np.full_like(self.base, float(self.base.mean()))
            span = float(self.base.max() - self.base.min())
            self.vmin = float(self.base.min()) - 0.10 * span
            self.vmax = float(self.base.max()) + 0.10 * span

        self.setAttribute(Qt.WA_DeleteOnClose, True)
        self.setFocusPolicy(Qt.StrongFocus)
        parent.installEventFilter(self)
        self.setGeometry(parent.rect())
        self.show()
        self.raise_()
        self.setFocus()

        self.clock = QElapsedTimer()
        self.clock.start()
        self._painted = False
        if self.base is not None:
            self._timer = QTimer(self)
            self._timer.timeout.connect(self._tick)
            self._timer.start(FRAME_MS)
        # Backstop: if the window never paints -- offscreen, minimised at
        # launch -- the screen must still go away.
        QTimer.singleShot(self.hold_ms + 3000, self.dismiss)

    # ---- state --------------------------------------------------------
    def set_status(self, text):
        """What the application is doing behind the screen."""
        self.status = str(text)
        self.update()

    def _tick(self):
        if self.clock.elapsed() > self.hold_ms + FADE_MS:
            self._stop_timer()
        self.update()

    def _stop_timer(self):
        if self._timer is not None:
            self._timer.stop()
            self._timer = None

    def frame(self, t_ms=None):
        """The surface at t milliseconds: built, waving, settling."""
        t = (self.clock.elapsed() if t_ms is None else t_ms) / 1000.0
        ny, nx = self.base.shape
        I, J = np.meshgrid(np.arange(nx), np.arange(ny))

        # rise out of the plane, column by column along rpm
        lead = (I / max(nx - 1, 1)) * (BUILD_MS * 0.55) / 1000.0
        a = np.clip((t - lead) / (BUILD_MS * 0.45 / 1000.0), 0.0, 1.0)
        a = a * a * (3.0 - 2.0 * a)
        v = self.flat + (self.base - self.flat) * a

        # a wave travelling over it, faded in after the build and out at the end
        rise = _ease((t - BUILD_MS / 1000.0) / 0.6)
        end = (self.hold_ms - SETTLE_MS) / 1000.0
        calm = 1.0 - _ease((t - end) / (SETTLE_MS / 1000.0))
        amp = 0.035 * (self.base.max() - self.base.min()) * rise * calm
        if amp > 0.0:
            phase = 2.0 * math.pi * (0.9 * I / nx + 0.6 * J / ny - 0.33 * t)
            v = v + amp * np.sin(phase)
        return v, t

    def camera(self, t):
        """Azimuth drifts while the surface moves, then stops where the
        cover art sits."""
        return -50.0 + 16.0 * _ease(t / max(self.hold_ms / 1000.0, 1e-3))

    # ---- painting -----------------------------------------------------
    def eventFilter(self, obj, ev):
        if obj is self.parent() and ev.type() in (QEvent.Resize, QEvent.Show):
            self.setGeometry(self.parent().rect())
            self._scaled = None
            self.raise_()
        return False

    def paintEvent(self, _ev):
        if not self._painted:
            # The clock starts at the first frame the user could actually
            # see, not at construction: unpacking, window mapping and the
            # maximise all happen before this, and any of it eaten from
            # the hold is animation nobody watched.
            self._painted = True
            self.clock.restart()
            QTimer.singleShot(self.hold_ms, self.dismiss)
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        p.fillRect(self.rect(), BG)
        w, h = self.width(), self.height()

        if self.base is not None:
            self._paint_surface(p, w, h)
        else:
            self._paint_still(p, w, h)
        self._paint_text(p, w, h)

    def _paint_surface(self, p, w, h):
        v, t = self.frame()
        zn = np.clip((v - self.vmin) / max(self.vmax - self.vmin, 1e-9), 0.0, 1.0)
        ny, nx = zn.shape
        I, J = np.meshgrid(np.arange(nx), np.arange(ny))
        X = I / max(nx - 1, 1) - 0.5
        Y = J / max(ny - 1, 1) - 0.5
        Z = zn * ZS - ZS / 2
        zoom = min(max(0.46 * w / max(0.66 * min(w, h), 1.0), 0.80), 1.7)
        # Lifted off centre to leave the lower left clear for the brand.
        px, py, pd = project(X, Y, Z, w, h, self.camera(t), 29.0, zoom, y_bias=-0.12)
        p.setPen(QPen(EDGE, 1))
        for poly, colour in quad_polys(px, py, pd, zn):
            p.setBrush(colour)
            p.drawPolygon(poly)

    def _paint_still(self, p, w, h):
        """No numpy, no tqmodel, or animation switched off: the painted art."""
        if self._fallback is None:
            path = asset("intro.png")
            if not path.exists():
                path = asset("splash.png")
            self._fallback = QPixmap(str(path)) if path.exists() else QPixmap()
        if self._fallback.isNull():
            return
        if self._scaled is None or self._scaled.size() != self.size() * 0.92:
            self._scaled = self._fallback.scaled(self.size() * 0.92, Qt.KeepAspectRatio,
                                                 Qt.SmoothTransformation)
        s = self._scaled
        p.drawPixmap((w - s.width()) // 2, (h - s.height()) // 2, s)

    def _brand(self):
        """The mark and the wordmark, loaded once. Either may be missing --
        a build made before they existed -- so the caller falls back to
        setting the name as text rather than drawing nothing."""
        if self._mark is None:
            self._mark = QPixmap(str(asset("brand-mark.png")))
            self._word = QPixmap(str(asset("brand-word.png")))
        return self._mark, self._word

    def brand_frame(self, w, h, t_ms=None):
        """Where the brand sits, and how far in it is, at t milliseconds.

        Pure geometry, so the sequence can be checked without painting:
        (mark_opacity, mark_rect, word_reveal, word_rect, baseline), or
        None if the art is missing. The rects are where each would be
        drawn fully; word_reveal is the fraction of the wordmark uncovered,
        measured from its left edge."""
        mark, word = self._brand()
        if mark.isNull() or word.isNull():
            return None

        t = self.clock.elapsed() if t_ms is None else t_ms
        base = h * MARK_BASE
        mh = h * MARK_H
        mw = mh * mark.width() / mark.height()
        x = w * MARK_LEFT

        # The mark settles the last few per cent of its size as it arrives,
        # so it lands rather than simply appearing.
        mark_in = _ease((t - MARK_AT_MS) / MARK_IN_MS)
        grow = 0.94 + 0.06 * mark_in
        mark_rect = QRectF(x, base - mh * grow, mw * grow, mh * grow)

        cap = mh * WORD_CAP
        wh = cap * self._word_cap_ratio()
        ww = wh * word.width() / word.height()
        word_rect = QRectF(x + mw + mh * WORD_GAP, base - wh, ww, wh)
        return mark_in, mark_rect, _ease((t - WORD_AT_MS) / WORD_IN_MS), word_rect, base

    def _paint_brand(self, p, w, h):
        """Returns the baseline the rest of the text hangs from, or None if
        the art could not be drawn."""
        state = self.brand_frame(w, h)
        if state is None:
            return None
        mark_in, mark_rect, word_in, word_rect, base = state
        if mark_in <= 0.0:
            return int(base)

        mark, word = self._brand()
        p.save()
        p.setOpacity(mark_in)
        p.drawPixmap(mark_rect, mark, QRectF(mark.rect()))
        p.setOpacity(1.0)
        if word_in > 0.0:
            # Revealed by an edge travelling right: the letters stay put
            # and the clip uncovers them in reading order, so the word
            # looks drawn out from behind the mark rather than flown in.
            p.setClipRect(QRectF(word_rect.x(), word_rect.y(),
                                 word_rect.width() * word_in, word_rect.height()))
            p.drawPixmap(word_rect, word, QRectF(word.rect()))
        p.restore()
        return int(base)

    @staticmethod
    def _word_cap_ratio():
        """The wordmark image's height as a multiple of its cap height.

        The art is trimmed to its ink, and "Lambda One" has no descenders,
        so the image runs from the baseline to the 'b' and 'd' ascenders.
        In Cormorant that is 725 units against a cap height of 625, plus
        13 units the 'a' and 'e' drop below the baseline: 1.181. Scaling
        by cap height rather than image height is what keeps the letters
        the same size as the specification if the wordmark is ever
        regenerated with different glyphs."""
        return 1.181

    def _paint_text(self, p, w, h):
        base = self._paint_brand(p, w, h)
        if base is None:
            title = QFont(self.font())
            title.setPixelSize(max(int(h * 0.058), 30))
            title.setBold(True)
            p.setFont(title)
            p.setPen(INK)
            p.drawText(QRect(int(w * MARK_LEFT), int(h * 0.62), w, int(h * 0.09)),
                       Qt.AlignLeft | Qt.AlignVCenter, "Lambda One")
            base = int(h * MARK_BASE)

        small = QFont("Consolas")
        small.setPixelSize(max(int(h * 0.020), 12))
        p.setFont(small)
        p.setPen(SUB)
        p.drawText(QRect(int(w * (MARK_LEFT + 0.002)), base + int(h * 0.035), w, int(h * 0.04)),
                   Qt.AlignLeft | Qt.AlignVCenter, "volumetric efficiency  ·  f(rpm, MAP)")

        p.setPen(DIM)
        p.drawText(QRect(int(w * (MARK_LEFT + 0.002)), h - int(h * 0.09), int(w * 0.8), int(h * 0.04)),
                   Qt.AlignLeft | Qt.AlignVCenter,
                   self.status or "engine simulator  ·  speed density  ·  lambda feedback")
        p.drawText(QRect(0, h - int(h * 0.06), w - int(w * 0.02), int(h * 0.04)),
                   Qt.AlignRight | Qt.AlignVCenter, f"version {APP_VERSION}")

    # ---- dismissal ----------------------------------------------------
    # A double-click on the desktop icon arrives as a click on the new
    # window, and launching from the Start menu ends with Enter. Both used
    # to dismiss the screen before anyone saw it, so input is ignored
    # until it has been up long enough to be deliberate.
    def _skippable(self):
        return self._painted and self.clock.elapsed() >= INPUT_GRACE_MS

    def mousePressEvent(self, _ev):
        if self._skippable():
            self.dismiss(0)

    def keyPressEvent(self, _ev):
        if self._skippable():
            self.dismiss(0)

    def dismiss(self, fade_ms=FADE_MS):
        # Not isVisible(): an overlay on a window that has not been shown
        # yet is invisible but very much alive, and skipping the teardown
        # there leaves its repaint timer running for the session.
        if self._done:
            return
        self._done = True
        if fade_ms <= 0:
            self._stop_timer()
            self.close()
            return
        effect = QGraphicsOpacityEffect(self)
        self.setGraphicsEffect(effect)
        self._fade = QPropertyAnimation(effect, b"opacity", self)
        self._fade.setDuration(fade_ms)
        self._fade.setStartValue(1.0)
        self._fade.setEndValue(0.0)
        self._fade.setEasingCurve(QEasingCurve.InQuad)
        self._fade.finished.connect(self._finish)
        self._fade.start()

    def _finish(self):
        self._stop_timer()
        self.close()


def intro_enabled() -> bool:
    """Remembered across runs, so it can be turned off for good."""
    from PySide6.QtCore import QSettings

    from .. import APP_NAME, ORG_NAME
    v = QSettings(ORG_NAME, APP_NAME).value("show_intro", True)
    return v not in (False, "false", "False", 0, "0")


def set_intro_enabled(on: bool) -> None:
    from PySide6.QtCore import QSettings

    from .. import APP_NAME, ORG_NAME
    QSettings(ORG_NAME, APP_NAME).setValue("show_intro", bool(on))


def show_intro(window, hold_ms=HOLD_MS, animate=True):
    """Cover `window` with the start-up screen. Returns the overlay, or
    None if there is nothing to draw with."""
    if animate:
        try:
            ve_surface(4, 4)
        except Exception:
            animate = False
    if not animate and not (asset("intro.png").exists() or asset("splash.png").exists()):
        return None
    return IntroOverlay(window, hold_ms=hold_ms, animate=animate)
